name: Publish Package to npmjs

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Git user info
        run: |
            git config --local user.email "action@snroe.com"
            git config --local user.name "GitHub Action"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm run build

      - name: Bump version and create tag
        run: |
            pnpm run release
        env:
            CI: true

      - name: Push version commit and tag
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.RELEASE_TOKEN }}@github.com/${{ github.repository }}
          git push origin main --follow-tags

      - id: publish
        name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false
          provenance: true
