name: Release on npm
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        
      - run: pnpm install
      - run: pnpm build
        
      - name: Generate changelog
        id: changelog
        env:
          CI: true
        run: |
          pnpm run release

      - name: Publish to NPM
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false
          provenance: true

      - name: Post-publish
        if: ${{ steps.publish.outputs.type }}
        run: |
          echo "Published ${{ steps.publish.outputs.type }} version: ${{ steps.publish.outputs.version }}"

      - name: Push version commit and tag
        if: ${{ steps.changelog.outputs.type }}
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          git config --local user.email "${{ secrets.ACTION_USERNAME }}"
          git config --local user.name "${{ secrets.ACTION_EMAIL }}"

          git push origin main
          git push origin tags --follow-tags

      - name: Read CHANGELOG.md
        id: readlog
        run: test -f CHANGELOG.md || exit 1
  
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: ${{ github.workspace }}/CHANGELOG.md
          draft: false
          prerelease: false
          token: ${{ github.token }}