name: Publish Package to npmjs

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "package.json"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
            bun-version: "latest"

      - name: Install dependencies
        run: |
          bun install

      - name: Build
        run: |
          bun run build

      - id: publish
        name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          dry-run: false
          provenance: true