name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read CHANGELOG.md
        id: readlog
        run: |
          if [ ! -f "$GITHUB_WORKSPACE/CHANGELOG.md" ]; then
            echo "ERROR: CHANGELOG.md not found in the root directory."
            exit 1
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: ${{ github.workspace }}/CHANGELOG.md
          draft: false
          prerelease: false
          token: ${{ secrets.RELEASE_TOKEN }}